# Generated by Django 2.2 on 2020-10-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Language')),
                ('level_1', models.CharField(max_length=50, verbose_name='Level 1')),
                ('level_2', models.CharField(max_length=50, verbose_name='Level 2')),
                ('level_3', models.CharField(max_length=50, verbose_name='Level 3')),
                ('level_4', models.CharField(max_length=50, verbose_name='Level 4')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaking_level', models.IntegerField(verbose_name='Speaking')),
                ('writting_level', models.IntegerField(verbose_name='Writting')),
                ('understanding_level', models.IntegerField(verbose_name='Understanding')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'LanguageLevel',
                'verbose_name_plural': 'LanguageLevels',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
