# Generated by Django 2.2 on 2020-10-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201029_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level_1',
            field=models.CharField(max_length=50, verbose_name='Niveau 1'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level_2',
            field=models.CharField(max_length=50, verbose_name='Niveau 2'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level_3',
            field=models.CharField(max_length=50, verbose_name='Niveau 3'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level_4',
            field=models.CharField(max_length=50, verbose_name='Niveau 4'),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='speaking_level',
            field=models.IntegerField(choices=[(1, 'Elémentaire'), (2, 'Pré-intermédiaire'), (3, 'Intermédiaire'), (4, 'Courrant')], verbose_name='Speaking'),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='understanding_level',
            field=models.IntegerField(choices=[(1, 'Elémentaire'), (2, 'Pré-intermédiaire'), (3, 'Intermédiaire'), (4, 'Courrant')], verbose_name='Understanding'),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='writting_level',
            field=models.IntegerField(choices=[(1, 'Elémentaire'), (2, 'Pré-intermédiaire'), (3, 'Intermédiaire'), (4, 'Courrant')], verbose_name='Writting'),
        ),
    ]
