# Generated by Django 2.2 on 2020-10-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201030_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagelevel',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Language', verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='speaking_level',
            field=models.IntegerField(choices=[(1, 'Elémentaire'), (2, 'Pré-intermédiaire'), (3, 'Intermédiaire'), (4, 'Courrant')], verbose_name='Parlé'),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='understanding_level',
            field=models.IntegerField(choices=[(1, 'Elémentaire'), (2, 'Pré-intermédiaire'), (3, 'Intermédiaire'), (4, 'Courrant')], verbose_name='Compréhension'),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='writting_level',
            field=models.IntegerField(choices=[(1, 'Elémentaire'), (2, 'Pré-intermédiaire'), (3, 'Intermédiaire'), (4, 'Courrant')], verbose_name='Ecrit'),
        ),
    ]
