# Generated by Django 2.2 on 2020-10-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201030_0855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='language',
            field=models.IntegerField(choices=[(1, 'Français'), (2, 'Anglais'), (3, 'Néerlandais')], verbose_name='Langue'),
        ),
    ]
